// Column labels in Exportify upstream, verified 2026-09-08. Shared source: fixtures/exportify/headers.json.
export const exportifyHeaders: Record<string, readonly string[]> = {
  track_uri: [
    'رابط الأغنية (URI)',
    'Track-URI',
    'URI κομματιού',
    'Track URI',
    'URI de la canción',
    'URI du titre',
    'URI della traccia',
    'トラックURI',
    'Nummer URI',
    'URI da faixa',
    'Låtens URI',
    'Parça URI',
  ],
  track_name: [
    'اسم الأغنية',
    'Track-Name',
    'Όνομα κομματιού',
    'Track Name',
    'Nombre de la canción',
    'Nom du titre',
    'Nome della traccia',
    'トラック名',
    'Nummernaam',
    'Nome da faixa',
    'Låtens namn',
    'Parça Adı',
  ],
  artist_names: [
    'أسماء الفنانين',
    'Künstlername(n)',
    'Όνομα/τα καλλιτέχνη',
    'Artist Name(s)',
    'Nombre(s) del artista',
    "Nom(s) de l'artiste",
    "Nome dell'artista",
    'アーティスト名',
    'Naam van artiest',
    'Nome(s) do artista',
    'Artistens namn',
    'Sanatçı Adı',
  ],
  album_name: [
    'اسم الألبوم',
    'Album-Name',
    'Όνομα άλμπουμ',
    'Album Name',
    'Nombre del álbum',
    "Nom de l'album",
    "Nome dell'album",
    'アルバム名',
    'Naam van album',
    'Nome do álbum',
    'Albumets namn',
    'Albüm Adı',
  ],
  track_duration: [
    'مدة الأغنية (بالمللي ثانية)',
    'Track-Dauer (ms)',
    'Διάρκεια κομματιού (ms)',
    'Track Duration (ms)',
    'Duración de la canción (ms)',
    'Durée du titre (ms)',
    'Durata della traccia (ms)',
    'トラックの長さ（ミリ秒）',
    'Nummerduur (ms)',
    'Duração da faixa (ms)',
    'Låtlängd (ms)',
    'Parça Süresi (ms)',
  ],
  added_at: [
    'أضيف في',
    'Hinzugefügt am',
    'Προστέθηκε στις',
    'Added At',
    'Añadido en',
    'Ajouté le',
    'Aggiunto il',
    '追加日時',
    'Toegevoegd op',
    'Adicionado em',
    'Tillagd vid',
    'Eklenme Tarihi',
  ],
}
